CREATE TABLE IF NOT EXISTS users
(
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_user   VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id_user),
    CONSTRAINT uq_email UNIQUE (email)
);
CREATE TABLE  IF NOT EXISTS categories
(
    id_cat BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_cat VARCHAR(200) NOT NULL,
    CONSTRAINT pk_cat PRIMARY KEY (id_cat),
    CONSTRAINT uq_name_cat UNIQUE (name_cat)
);
CREATE TABLE IF NOT EXISTS events
(
    id_event BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    id_cat BIGINT NOT NULL,
    confirmed_requests BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    id_initiator BIGINT NOT NULL REFERENCES users (id_user),
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(100) NOT NULL,
    title VARCHAR(130) NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id_event),
    CONSTRAINT fk_events_cat FOREIGN KEY (id_cat) REFERENCES categories (id_cat)
    );
CREATE TABLE IF NOT EXISTS requests
(
    id_req BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    id_event BIGINT NOT NULL,
    id_user BIGINT NOT NULL,
    status VARCHAR(100),
    CONSTRAINT pk_request PRIMARY KEY (id_req),
    CONSTRAINT fk_request_event FOREIGN KEY (id_event) REFERENCES events (id_event),
    CONSTRAINT fk_request_user FOREIGN KEY (id_user) REFERENCES users (id_user)
);
CREATE TABLE IF NOT EXISTS compilations
(
    id_compilations BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(200) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id_compilations)
);
CREATE TABLE IF NOT EXISTS events_compilations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_comp BIGINT NOT NULL,
    id_event BIGINT NOT NULL,
    CONSTRAINT pk_ev_comp PRIMARY KEY (id),
    CONSTRAINT fk_comp FOREIGN KEY (id_comp) REFERENCES compilations (id_compilations),
    CONSTRAINT fk_event FOREIGN KEY (id_event) REFERENCES events (id_event)
);


